<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Recipe.Domain\Recipe.Domain.csproj" />
    <ProjectReference Include="..\Recipe.Infrastructure\Recipe.Infrastructure.csproj" />
  </ItemGroup>

</Project>
